# Generated by Django 5.2.7 on 2025-10-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participnats',
            new_name='participants',
        ),
    ]
